### ISSUE TITLE
Dataloader error

### ISSUE THREAD

**Issue by Wujingqian** [facebookresearch/silk#15] opened 2023-04-26 04:55 UTC
Hi,
Thank you so much for this fantastic work!
I want to reproduce the training on coco datasets, so I download the dataset and changed the configuration path. However, when I tried to train, this error pop up when loading validation data for the validation sanity check:: pytorch_lightning.utilities.exceptions.MisconfigurationException: Total length of `Dataloader` across ranks is zero. Please make sure that it returns at least 1 batch.

After some debugging, I find that the dataloader was not created correctly: it was empty and had a length of zero.
However, I can't figure out a reason for this. Everything seemed to make sense: the folder has images in it, the path is correct, and the configuration has changed correspondingly. Here is a screenshot of the configuration that it used to produce dataloader by the hydra lib:
![image](https://user-images.githubusercontent.com/30253939/234473279-991f2f62-0fdf-4714-a1c2-d4b9fad68b15.png)

Could someone see what am I doing wrong?
Many thanks!!!

**Comment by Speng-bjtu** [comment] 2023-04-26 09:22
hello i meet the same error. are you fix it ?

**Comment by gleize** [comment] 2023-04-26 18:30
Hi @Wujingqian, @Speng-bjtu,

The `CocoCaptions` class seems to be loading images **only** when an annotation file is provided (even though SiLK does not use any annotations).

I see your `annFile` is set to `None`, so this is likely the cause.

You can run this minimal code below to confirm :

```python
from torchvision.datasets import CocoCaptions

ROOT = "/datasets01/COCO/022719/train2017"

ANN_FILE = None # produces dataset of size 0
ANN_FILE = "/datasets01/COCO/022719/annotations/captions_train2017.json" # works

dataset = CocoCaptions(root=ROOT, annFile=ANN_FILE)

print(len(dataset))
```

**Comment by Speng-bjtu** [comment] 2023-04-27 02:50
yes you are right, but in your doc the setting of dataset  is:

**Once downloaded, update the path root in the configuration files ./etc/datasets/coco/{training,validation,test}.yaml. The field annFile can be set to null since SiLK does not use any annotation.**

i fellow the step and meet the error, maybe you could fix it

**Comment by gleize** [comment] 2023-04-27 20:23
@Speng-bjtu

Thanks for point out the issue from the documentation. It shouldn't be there and I'll fix that right away.

**Comment by gleize** [comment] 2023-04-27 23:45
Fixed [here](https://github.com/facebookresearch/silk/commit/9d80ebd81212c75d3638bd2d77c18bc48af7f5b5).
Closing now.

**Closed by gleize** 2023-04-27 23:45 UTC
