### ISSUE TITLE
use superpoint to inference

### ISSUE THREAD

**Issue by tianszh-000** [facebookresearch/silk#26] opened 2023-07-04 09:21 UTC
hi, i want to inference with ur trained superpoint parameters
here is my use of your cli_tool, 
`#!/bin/bash
set -e

# folders param
TAG=testResult_coco_1_sppoint4 #example
IMAGES=/data/SiLK/dataset/case2  #$MY_IMAGES
IMAGES_EXTENSION=jpg
OUT=var/cli/$TAG

# model / matching params
CHECKPOINT="/data/SiLK/silk/assets/tests/magicpoint/superpoint_v1.pth"
TOPK=10000
SIZE=480

mkdir -p $OUT

# extract features
./bin/silk-features -o -m superpoint -c $CHECKPOINT -k $TOPK -d $OUT/features -s $SIZE $IMAGES/*.$IMAGES_EXTENSION
# generate image pairs to match
ls $OUT/features/*.pt | sort -V | xargs ./bin/generate-matches exhaustive -s > $OUT/matches.txt
# match keypoints from generated image pairs
./bin/silk-matching -o -m double-softmax -t 0.9 $OUT/matches.txt $OUT/matches/
# visualize matches
./bin/silk-viz image -o $OUT/viz $OUT/matches/*.pt`

and i keep encountered with problem like this:
ERROR    | __main__:<module>:131 - cannot load file : var/cli/testResult_coco_1_sppoint4/matches/*.pt
RuntimeError: The size of tensor a (65) must match the size of tensor b (60) at non-singleton dimension 0

so is there anything wrong with the cli-tool configuration, or there are other ways to do this?

**Comment by gleize** [comment] 2023-07-04 16:16
Hi @tianszh-000,

Thanks for pointing out the issue. There was indeed a bug when running the SuperPoint model, the feature output format was incorrect, which lead to the exception mentioned above.

I've pushed a fix, but it will some time to land in the Meta codebase and sync on Github. In the meantime, you can apply the fix by replacing this [line](https://github.com/facebookresearch/silk/blob/1571859e11eb009d8028c7975c87c7ef42882428/bin/silk-features#L149) by this :
```python
        kwargs = {
            "use_batchnorm": False,
            "default_outputs": ("positions", "sparse_descriptors"),
        }
```

**Comment by tianszh-000** [comment] 2023-07-05 09:27
> Hi @tianszh-000,
> 
> Thanks for pointing out the issue. There was indeed a bug when running the SuperPoint model, the feature output format was incorrect, which lead to the exception mentioned above.
> 
> I've pushed a fix, but it will some time to land in the Meta codebase and sync on Github. In the meantime, you can apply the fix by replacing this [line](https://github.com/facebookresearch/silk/blob/1571859e11eb009d8028c7975c87c7ef42882428/bin/silk-features#L149) by this :
> 
> ```python
>         kwargs = {
>             "use_batchnorm": False,
>             "default_outputs": ("positions", "sparse_descriptors"),
>         }
> ```

that works, and i met another problem when i tried "out-of-framework-model evaluation"  by executing ./bin/silk-cli mode=run-hpatches-tests-cached-disk
error like this:
ModuleNotFoundError: Caught ModuleNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/xxx/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/xxx/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/xxx/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/xxx/silk/silk/datasets/cached.py", line 87, in __getitem__
    return pickle.loads(obj_bytes)
ModuleNotFoundError: No module named 'pixenv'
is this a bug too? or is there anything wrong with my steps?

**Comment by gleize** [comment] 2023-07-05 21:14
Hi @tianszh-000,

Thanks for pointing that out.

There is indeed an issue with the pickle loading of cached dataset. Those datasets were saved to disk using the old codebase named `pixenv`, which created the above exception when loading those files in the newly renamed codebase.

A fix has been pushed [here](https://github.com/facebookresearch/silk/commit/9943c1ca4e7659b1d755e413e7eeb8f5f311a254).

This issue should only affect the pickle files we do provide, it should not affect the cached dataset you created though.

**Comment by tianszh-000** [comment] 2023-07-06 03:28
u r right, there is still error after using ur bugfix
here is my error when i ./bin/silk-cli mode=run-hpatches-tests-cached-model_name
`points1 = torch.vstack((points1, torch.ones(1, num_points, device=points1.device)))
              │     │       │        │     │       │                  │       └ <attribute 'device' of 'torch._C._TensorBase' objects>
              │     │       │        │     │       │                  └ tensor([[[[0.6078]],
              │     │       │        │     │       │                    
              │     │       │        │     │       │                             [[0.6078]],
              │     │       │        │     │       │                    
              │     │       │        │     │       │                             [[0.5961]],
              │     │       │        │     │       │                    
              │     │       │        │     │       │                             [[0.6000]],
              │     │       │        │     │       │                    
              │     │       │        │     │       │                             [[0.6510]],
              │     │       │        │     │       │                    
              │     │       │        │     │       │                             [[0.69...
              │     │       │        │     │       └ 480
              │     │       │        │     └ <built-in method ones of type object at 0x7fbb220e6760>
              │     │       │        └ <module 'torch' from '/data/miniconda3/envs/silk/lib/python3.8/site-packages/torch/__init__.py'>
              │     │       └ tensor([[[[0.6078]],
              │     │         
              │     │                  [[0.6078]],
              │     │         
              │     │                  [[0.5961]],
              │     │         
              │     │                  [[0.6000]],
              │     │         
              │     │                  [[0.6510]],
              │     │         
              │     │                  [[0.69...
              │     └ <built-in method vstack of type object at 0x7fbb220e6760>
              └ <module 'torch' from '/data/miniconda3/envs/silk/lib/python3.8/site-packages/torch/__init__.py'>

RuntimeError: Tensors must have same number of dimensions: got 4 and 2
`
and i think there is sth wrong with my generated hd5 file
well, i want to evaluate my own superpoint model (trained on other datasets)in ur framework, and according to my understanding about ur out-framework-model-evaluation doc, i should generate a match-point dataset with my won model and ur provided cached dataset, my understanding is that ur "run-on-hpatches-model-name" script would compute keypoints with my model info, i don't know if that's right, my run-on-hpatches-model script like this, bascially ,i just pieces components together with the scripts u provide, but i am not sure if this is right way
`DATASET = "/xxx/assets/datasets/cached-hpatches/hpatches-full-size-480-grey.h5"
OUTPUT_DATASET = "Spoint_all_points_480.h5"
MODEL_WEIGHT = "/xxx/assets/models/silk/analysis/alpha/spp_5_1.674.pth"


def mnn_matcher(descriptors_a, descriptors_b):
    device = descriptors_a.device
    sim = descriptors_a @ descriptors_b.t()
    nn12 = torch.max(sim, dim=1)[1]
    nn21 = torch.max(sim, dim=0)[1]
    ids1 = torch.arange(0, sim.shape[0], device=device)
    mask = ids1 == nn21[nn12]
    matches = torch.stack([ids1[mask], nn12[mask]])
    return matches.t().data.cpu().numpy()


def transform(elem, matcher):
    # extract images (single image, no batch dimension)
    original_image = elem["original_img"]
    warped_image = elem["warped_img"]

    original_image = original_image[None].cuda()
    warped_image = warped_image[None].cuda()
    batch = {"image0": original_image, "image1": warped_image}
    print("batch",batch)
    with torch.no_grad():
        matcher(batch)
        mkpts0 = batch["image0"].cpu()
        mkpts1 = batch["image1"].cpu()
        # mconf = batch["mconf"].cpu()  # noqa: F841

    # run model here
    original_points = mkpts0[..., [1, 0]]
    warped_points = mkpts1[..., [1, 0]]
    matched_original_points = mkpts0[..., [1, 0]]
    matched_warped_points = mkpts1[..., [1, 0]]

    # save keypoints
    elem = elem.add("original_points", original_points)
    elem = elem.add("warped_points", warped_points)
    elem = elem.add("matched_original_points", matched_original_points)
    elem = elem.add("matched_warped_points", matched_warped_points)

    return elem



def main():
    # load model
    state_dict = torch.load(MODEL_WEIGHT, map_location="cpu")
    print(list(state_dict.keys()))
    if "extractor" in state_dict:
        weights = state_dict["extractor"]
    # elif "disk" in state_dict:
    #     weights = state_dict["disk"]
    else:
        weights = state_dict
        # raise KeyError("Incompatible weight file!")

    model = SuperPointBNNet()
    model.load_state_dict(weights)
    model = model.cuda()
    model = model.eval()

    cache(DATASET, OUTPUT_DATASET, transform, model)


if __name__ == "__main__":
    main()
`
is there any solutions to slove this? thanks very much

**Comment by gleize** [comment] 2023-07-06 06:33
Hi @tianszh-000,

> [...], but i am not sure if this is the right way

Your understanding is correct, this is the right way.

> is there any solutions to slove this? 

Based on the exception output, it seems the shape of the keypoint positions is incorrect.
Looking at your code, it seems you're using the images as keypoints :
```python
        mkpts0 = batch["image0"].cpu()
        mkpts1 = batch["image1"].cpu()
```
This won't work for sure.

Once you fix the issue, make sure `original_points`, `warped_points`, `matched_original_points` and `matched_warped_points` have the proper shape ($N\times2$) and ordering of the position coordinates (`yx`).

**Comment by tianszh-000** [comment] 2023-07-12 03:00
hi
how can i make the 
original_image = elem["original_img"]
warped_image = elem["warped_img"]
work? my original_Image and warped image seems to be the same one, and i don't know how to make it work because the ur code framework is kinda complicated, as well as the matches, my run-on-hpatches script run as below:
``def transform(elem, model):
    # extract images (single image, no batch dimension)
    original_image = elem["original_img"]
    warped_image = elem["warped_img"]
    # print("elem",elem)
    original_image = original_image[None].cuda()
    warped_image = warped_image[None].cuda()
    batch = {"image0": original_image, "image1": warped_image}
    print("batch",batch)
    conf_threshold=0
    with torch.no_grad():
        output0 = model(batch["image0"])
        print(batch["image0"].size())
        print("ret",output0)
        # print("ret",output0,list(output0.keys()),list(output0['det_info'].keys()),list(output0['desc_info'].keys()))
        prob = output0[0].cpu().numpy().squeeze()
        descriptors0 = output0[1].cpu().numpy().squeeze()
        pos = np.where(prob > conf_threshold)
        keypoints_0 = np.array(np.stack(pos).T).astype(np.float64) # y, x
        des0 = []
        score = []
        for i in range(np.array(pos).shape[1]):
            x, y = pos[0][i], pos[1][i]
            des0.append(descriptors0[:, x, y])
            score.append(prob[x, y])
        des0 = np.array(des0)
        score = np.array(score)
        kps_0 = keypoints_0.copy()
        kps_0[:, 0] = keypoints_0[:, 1]
        kps_0[:, 1] = keypoints_0[:, 0]
        print("score",score,score.shape,"kps_output", kps_0,kps_0.shape,"des_output",des0,des0.shape)
        mkpts0 =kps_0
        original_points= mkpts0

        output1 = model(batch["image1"])
        print(batch["image1"].size())
        print("ret1",output1)
        # print("ret",output0,list(output0.keys()),list(output0['det_info'].keys()),list(output0['desc_info'].keys()))
        prob1 = output1[0].cpu().numpy().squeeze()
        descriptors1 = output1[1].cpu().numpy().squeeze()
        pos1 = np.where(prob > conf_threshold)
        keypoints_1 = np.array(np.stack(pos1).T).astype(np.float64) # y, x
        des1 = []
        score1 = []
        for i in range(np.array(pos1).shape[1]):
            x1, y1 = pos1[0][i], pos1[1][i]
            des1.append(descriptors1[:, x, y])
            score1.append(prob1[x, y])
        des1 = np.array(des1)
        score1 = np.array(score1)
        kps_1 = keypoints_1.copy()
        kps_1[:, 0] = keypoints_1[:, 1]
        kps_1[:, 1] = keypoints_1[:, 0]
        # print("score",score1,score1.shape,"kps_output", kps_1,kps_1.shape,"des_output",des1,des1.shape)
        mkpts1 =kps_1
        warped_points = mkpts1
        
        print("mkpts of superpoint:",mkpts0,mkpts1,mkpts1.shape)
    #     print("des_0_1",des0.shape)
        print("des of superpoint:",des0,des1,des0.shape,des1.shape)

           # save keypoints
        original_points=torch.from_numpy(original_points)
        warped_points=torch.from_numpy(warped_points)
        des0,des1=torch.from_numpy(des0),torch.from_numpy(des1)         
        score,score1=torch.from_numpy(score),torch.from_numpy(score1)
        o_xys, o_desc, o_scores = postprocess_results(original_points, des0, score)
        w_xys, w_desc, w_scores = postprocess_results(warped_points, des1, score1)

        with torch.no_grad():
            matches = mnn_matcher(
                torch.from_numpy(o_desc), torch.from_numpy(w_desc)
            )
        
        
        # matched_original_points=torch.from_numpy(mkpts0)
        # matched_warped_points = torch.from_numpy(mkpts1)
        


    # # run model here
    # # original_points = mkpts0[..., [1, 0]]
    print("original_points",original_points)
    # warped_points = mkpts1[..., [1, 0]]
    print("warped_points",warped_points)

    
 
    # matches=mnn_matcher(des0,des1)

    # matched_original_points=torch.from_numpy(matched_original_points)
    # matched_warped_points=torch.from_numpy(matched_warped_points)


    elem = elem.add("original_points", original_points.type(torch.float32))
    elem = elem.add("warped_points", warped_points.type(torch.float32))
    # elem = elem.add("matched_original_points", matched_original_points)
    # elem = elem.add("matched_warped_points", matched_warped_points)
    elem = elem.add("original_desc", des0.type(torch.float32))
    elem = elem.add("warped_desc",des1.type(torch.float32) )

    # print("review:",original_points,warped_points,matched_original_points,matched_warped_points)
    
    return elem
``
results of the script:
``
original_points tensor([[197.,  13.], 
        [193.,  14.],
        [224.,  24.],
        [161.,  26.],
        [217.,  26.],
        [173.,  27.],
        [213.,  27.],
        [137.,  29.],
        [200.,  29.],
        [223.,  32.],
        [151.,  33.],
        [167.,  33.],
        [205.,  33.],
        [142.,  36.],
        [112.,  37.],
        [127.,  37.],
        [228.,  37.],
        [199.,  38.],
        [147.,  40.],
        [182.,  40.],
        [117.,  41.],
        [214.,  41.],
        [159.,  42.],
        [123.,  45.],
        [136.,  45.],
        [180.,  45.],
        [190.,  45.],
        [102.,  46.],
        [210.,  46.],
        [140.,  48.],
        [233.,  48.],
        [134.,  49.],
        [112.,  51.],
        [154.,  51.],
        [ 86.,  52.],
        [ 93.,  53.],
        [234.,  53.],
        [119.,  54.],
        [100.,  55.],
        [176.,  56.],
        [193.,  59.],
        [ 81.,  63.],
        [ 93.,  64.],
        [191.,  65.],
        [220.,  65.],
        [ 72.,  67.],
        [ 81.,  67.],
        [187.,  67.],
        [212.,  67.],
        [ 94.,  68.],
        [201.,  68.],
        [116.,  71.],
        [ 75.,  72.],
        [125.,  73.],
        [155.,  73.],
        [ 82.,  74.],
        [ 49.,  76.],
        [ 64.,  77.],
        [173.,  77.],
        [ 46.,  78.],
        [138.,  79.],
        [155.,  81.],
        [188.,  81.],
        [201.,  81.],
        [183.,  83.],
        [213.,  83.],
        [ 80.,  88.],
        [143.,  88.],
        [ 42.,  91.],
        [ 99.,  93.],
        [146.,  94.],
        [199.,  94.],
        [116.,  95.],
        [139.,  95.],
        [170.,  96.],
        [189.,  98.],
        [122.,  99.],
        [217., 100.],
        [227., 100.],
        [ 34., 101.],
        [ 47., 101.],
        [152., 101.],
        [100., 103.],
        [134., 103.],
        [146., 104.],
        [170., 105.],
        [188., 106.],
        [ 75., 107.],
        [151., 108.],
        [201., 108.],
        [193., 109.],
        [197., 109.],
        [219., 110.],
        [140., 111.],
        [ 31., 112.],
        [161., 112.],
        [ 95., 114.],
        [ 38., 115.],
        [170., 116.],
        [ 81., 119.],
        [ 89., 119.],
        [227., 119.],
        [ 23., 120.],
        [ 99., 125.],
        [206., 125.],
        [ 22., 127.],
        [ 79., 129.],
        [110., 131.],
        [143., 131.],
        [ 22., 132.],
        [148., 132.],
        [ 74., 133.],
        [101., 133.],
        [ 17., 137.],
        [ 88., 137.],
        [158., 137.],
        [ 30., 139.],
        [ 21., 141.],
        [226., 141.],
        [166., 142.],
        [144., 145.],
        [ 19., 146.],
        [ 26., 148.],
        [ 62., 148.],
        [166., 151.],
        [ 51., 152.],
        [206., 154.],
        [223., 155.],
        [125., 156.],
        [129., 157.],
        [ 31., 159.],
        [118., 159.],
        [206., 162.],
        [175., 163.],
        [228., 163.],
        [ 45., 165.],
        [103., 166.],
        [189., 166.],
        [148., 168.],
        [201., 169.],
        [221., 171.],
        [141., 178.],
        [165., 178.],
        [ 61., 179.],
        [176., 180.],
        [157., 181.],
        [ 65., 182.],
        [148., 182.],
        [213., 182.],
        [ 44., 183.],
        [ 79., 183.],
        [196., 183.],
        [187., 186.],
        [ 51., 188.],
        [ 94., 189.],
        [ 66., 190.],
        [166., 190.],
        [234., 191.],
        [ 70., 194.],
        [ 77., 195.],
        [ 98., 198.],
        [186., 198.],
        [ 77., 200.],
        [ 86., 200.],
        [181., 201.],
        [103., 207.],
        [135., 208.],
        [111., 209.],
        [152., 210.],
        [ 93., 211.],
        [133., 211.],
        [189., 211.],
        [219., 212.],
        [229., 214.],
        [170., 215.],
        [154., 217.],
        [177., 218.],
        [223., 218.],
        [114., 221.],
        [123., 223.],
        [211., 225.],
        [173., 227.],
        [187., 227.],
        [231., 227.],
        [135., 228.],
        [203., 229.],
        [156., 230.],
        [145., 232.],
        [221., 232.],
        [175., 233.]], dtype=torch.float64)
warped_points tensor([[197.,  13.],
        [193.,  14.],
        [224.,  24.],
        [161.,  26.],
        [217.,  26.],
        [173.,  27.],
        [213.,  27.],
        [137.,  29.],
        [200.,  29.],
        [223.,  32.],
        [151.,  33.],
        [167.,  33.],
        [205.,  33.],
        [142.,  36.],
        [112.,  37.],
        [127.,  37.],
        [228.,  37.],
        [199.,  38.],
        [147.,  40.],
        [182.,  40.],
        [117.,  41.],
        [214.,  41.],
        [159.,  42.],
        [123.,  45.],
        [136.,  45.],
        [180.,  45.],
        [190.,  45.],
        [102.,  46.],
        [210.,  46.],
        [140.,  48.],
        [233.,  48.],
        [134.,  49.],
        [112.,  51.],
        [154.,  51.],
        [ 86.,  52.],
        [ 93.,  53.],
        [234.,  53.],
        [119.,  54.],
        [100.,  55.],
        [176.,  56.],
        [193.,  59.],
        [ 81.,  63.],
        [ 93.,  64.],
        [191.,  65.],
        [220.,  65.],
        [ 72.,  67.],
        [ 81.,  67.],
        [187.,  67.],
        [212.,  67.],
        [ 94.,  68.],
        [201.,  68.],
        [116.,  71.],
        [ 75.,  72.],
        [125.,  73.],
        [155.,  73.],
        [ 82.,  74.],
        [ 49.,  76.],
        [ 64.,  77.],
        [173.,  77.],
        [ 46.,  78.],
        [138.,  79.],
        [155.,  81.],
        [188.,  81.],
        [201.,  81.],
        [183.,  83.],
        [213.,  83.],
        [ 80.,  88.],
        [143.,  88.],
        [ 42.,  91.],
        [ 99.,  93.],
        [146.,  94.],
        [199.,  94.],
        [116.,  95.],
        [139.,  95.],
        [170.,  96.],
        [189.,  98.],
        [122.,  99.],
        [217., 100.],
        [227., 100.],
        [ 34., 101.],
        [ 47., 101.],
        [152., 101.],
        [100., 103.],
        [134., 103.],
        [146., 104.],
        [170., 105.],
        [188., 106.],
        [ 75., 107.],
        [151., 108.],
        [201., 108.],
        [193., 109.],
        [197., 109.],
        [219., 110.],
        [140., 111.],
        [ 31., 112.],
        [161., 112.],
        [ 95., 114.],
        [ 38., 115.],
        [170., 116.],
        [ 81., 119.],
        [ 89., 119.],
        [227., 119.],
        [ 23., 120.],
        [ 99., 125.],
        [206., 125.],
        [ 22., 127.],
        [ 79., 129.],
        [110., 131.],
        [143., 131.],
        [ 22., 132.],
        [148., 132.],
        [ 74., 133.],
        [101., 133.],
        [ 17., 137.],
        [ 88., 137.],
        [158., 137.],
        [ 30., 139.],
        [ 21., 141.],
        [226., 141.],
        [166., 142.],
        [144., 145.],
        [ 19., 146.],
        [ 26., 148.],
        [ 62., 148.],
        [166., 151.],
        [ 51., 152.],
        [206., 154.],
        [223., 155.],
        [125., 156.],
        [129., 157.],
        [ 31., 159.],
        [118., 159.],
        [206., 162.],
        [175., 163.],
        [228., 163.],
        [ 45., 165.],
        [103., 166.],
        [189., 166.],
        [148., 168.],
        [201., 169.],
        [221., 171.],
        [141., 178.],
        [165., 178.],
        [ 61., 179.],
        [176., 180.],
        [157., 181.],
        [ 65., 182.],
        [148., 182.],
        [213., 182.],
        [ 44., 183.],
        [ 79., 183.],
        [196., 183.],
        [187., 186.],
        [ 51., 188.],
        [ 94., 189.],
        [ 66., 190.],
        [166., 190.],
        [234., 191.],
        [ 70., 194.],
        [ 77., 195.],
        [ 98., 198.],
        [186., 198.],
        [ 77., 200.],
        [ 86., 200.],
        [181., 201.],
        [103., 207.],
        [135., 208.],
        [111., 209.],
        [152., 210.],
        [ 93., 211.],
        [133., 211.],
        [189., 211.],
        [219., 212.],
        [229., 214.],
        [170., 215.],
        [154., 217.],
        [177., 218.],
        [223., 218.],
        [114., 221.],
        [123., 223.],
        [211., 225.],
        [173., 227.],
        [187., 227.],
        [231., 227.],
        [135., 228.],
        [203., 229.],
        [156., 230.],
        [145., 232.],
        [221., 232.],
        [175., 233.]], dtype=torch.float64)
matches: tensor([[53],
        [ 0]]) (basically, it's always a 1x2 dimension)
``
the evlauation results of my own model, other metrics is 0 except repeatbility, and i am not sure if the repeatibility is right....

**Comment by tianszh-000** [comment] 2023-07-17 07:36
hi, i have two questions about training.
1. model params files saved during training process, which one should be chosen to be the final very best model to evalaute?  i used the lastest one "epoch=99-step=99999.ckpt" to evlauate on hpatches, the metrics showing worse than using "epoch=38-step=38999.ckpt"
2. in terms of our training conditions with only one GPU (Quadro RTX A6000), I modified the code to train under one GPU, it runs well but i don't know if that brings some accuracy gap cause u mentioned it has to be at least two GPUs.

**Comment by gleize** [comment] 2023-07-17 14:46
Hi @tianszh-000 ,

> in terms of our training conditions with only one GPU (Quadro RTX A6000), I modified the code to train under one GPU, it runs well but i don't know if that brings some accuracy gap cause u mentioned it has to be at least two GPUs.

It shouldn't affect the performance. The two GPU requirement was more of a "hard-coded convenience" than anything else.

> model params files saved during training process(training with only one gpu), which one should be chosen to be the final very best model to evalaute? i used the lastest one "epoch=99-step=99999.ckpt" to evlauate on hpatches, the metrics showing worse than using "epoch=38-step=38999.ckpt", while using "epoch=38-step=38999.ckpt", metrics even better than the one u listed in ur article.

In all of our training, we selected the **last checkpoint** among the best 10 (best in term of validation score). And we trained only once (i.e. we didn't train multiple times and selected the model having best results on our benchmarks). So, what you've found is interesting, but not too surprising. It's likely caused by the stochastic nature of the training. It would be interesting to measure the variance of those results over multiple trainings, and whether or not "early" checkpoints have consistently better performance than later ones.

**Closed** 2023-07-28 15:39 UTC
